version: '3.8'

services:
  mongo-config1:
    image: mongo:4.4
    container_name: mongo-config1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--bind_ip_all"]
    ports:
      - 27019:27019
    volumes:
      - mongo-config1-data:/data/configdb
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-config1:/external_storage
    networks:
      - mongo-cluster

  mongo-config2:
    image: mongo:4.4
    container_name: mongo-config2
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27020", "--bind_ip_all"]
    ports:
      - 27020:27020
    volumes:
      - mongo-config2-data:/data/configdb
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-config2:/external_storage
    networks:
      - mongo-cluster

  mongo-config3:
    image: mongo:4.4
    container_name: mongo-config3
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27021", "--bind_ip_all"]
    ports:
      - 27021:27021
    volumes:
      - mongo-config3-data:/data/configdb
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-config3:/external_storage
    networks:
      - mongo-cluster

  mongo-shard1:
    image: mongo:4.4
    container_name: mongo-shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27022", "--bind_ip_all"]
    ports:
      - 27022:27022
    volumes:
      - mongo-shard1-data:/data/db
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-shard1:/external_storage
    networks:
      - mongo-cluster

  mongo-shard2:
    image: mongo:4.4
    container_name: mongo-shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27023", "--bind_ip_all"]
    ports:
      - 27023:27023
    volumes:
      - mongo-shard2-data:/data/db
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-shard2:/external_storage
    networks:
      - mongo-cluster

  mongo-router:
    image: mongo:4.4
    container_name: mongo-router
    command: ["mongos", "--configdb", "configReplSet/mongo-config1:27019,mongo-config2:27020,mongo-config3:27021", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - mongo-router-data:/data/db
      - /Users/jiny/Desktop/Project/SchoolProject/BigDataStructure/external_storage/mongo-router:/external_storage
    networks:
      - mongo-cluster

volumes:
  mongo-config1-data:
  mongo-config2-data:
  mongo-config3-data:
  mongo-shard1-data:
  mongo-shard2-data:
  mongo-router-data:

networks:
  mongo-cluster:
    driver: bridge
